# typed: false
# frozen_string_literal: true

# This is a placeholder. The real formula will be generated by GoReleaser
# during the release process.
class CursorRules < Formula
  desc "CLI tool to help initialize and manage Cursor Editor rules for your projects"
  homepage "https://github.com/fireharp/cursor-rules"
  version "0.0.0"
  license "MIT"

  # This is a placeholder. The real URLs and checksums will be generated by GoReleaser.
  # This placeholder formula cannot be installed.
  
  def caveats
    <<~EOS
      This is a placeholder formula. 
      Please wait for the first official release to be published.
      
      Run cursor-rules in your project directory to set up Cursor Editor rules
    EOS
  end
end 