# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CursorRules < Formula
  desc "CLI tool to help initialize and manage Cursor Editor rules for your projects"
  homepage "https://github.com/fireharp/cursor-rules"
  version "0.1.3-SNAPSHOT-8915dc0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fireharp/cursor-rules/releases/download/v0.1.3/cursor-rules_Darwin_x86_64.tar.gz"
      sha256 "4c137564fe6948f9b1a36cdddfd142334eac9862cbecbae00731f1a291a113ce"

      def install
        bin.install "cursor-rules"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fireharp/cursor-rules/releases/download/v0.1.3/cursor-rules_Darwin_arm64.tar.gz"
      sha256 "1bd478ecab9f1553965853d78db79b5b1c41ba37368bc1bf27c8ed7671f1e23e"

      def install
        bin.install "cursor-rules"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fireharp/cursor-rules/releases/download/v0.1.3/cursor-rules_Linux_x86_64.tar.gz"
        sha256 "7391a59dac5af6a373626d1d31a06debba5bbbe0c4a4b6ed00aaaed6f9327787"

        def install
          bin.install "cursor-rules"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fireharp/cursor-rules/releases/download/v0.1.3/cursor-rules_Linux_arm64.tar.gz"
        sha256 "46b8da404659ea0699e9c62efeac166500c3fc31cea3a47645a4e838cfa9358a"

        def install
          bin.install "cursor-rules"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run cursor-rules in your project directory to set up Cursor Editor rules
    EOS
  end

  test do
    system "#{bin}/cursor-rules --version"
  end
end
