# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CursorRules < Formula
  desc "CLI tool to help initialize and manage Cursor Editor rules for your projects"
  homepage "https://github.com/fireharp/cursor-rules"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fireharp/cursor-rules/releases/download/v0.1.3/cursor-rules_Darwin_x86_64.tar.gz"
      sha256 "2f5fc16aef1ca82b2e825a2bb772864a891ff3135d4dec796fb9706649819ae0"

      def install
        bin.install "cursor-rules"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fireharp/cursor-rules/releases/download/v0.1.3/cursor-rules_Darwin_arm64.tar.gz"
      sha256 "153975547a6e38a7514b1d37454ba2db030b22b7213fc83f8d23d8c8b500bcb6"

      def install
        bin.install "cursor-rules"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fireharp/cursor-rules/releases/download/v0.1.3/cursor-rules_Linux_x86_64.tar.gz"
        sha256 "b0d3e74d67361dbbe6e56fd9af3abc042d971881fd7a0a98906f34b3cc22f123"

        def install
          bin.install "cursor-rules"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/fireharp/cursor-rules/releases/download/v0.1.3/cursor-rules_Linux_arm64.tar.gz"
        sha256 "b619e25425918f9f16d488cba18b9d7c039b7cc0dde25b9b55a98f254030a593"

        def install
          bin.install "cursor-rules"
        end
      end
    end
  end

  def caveats
    <<~EOS
      Run cursor-rules in your project directory to set up Cursor Editor rules
    EOS
  end

  test do
    system "#{bin}/cursor-rules --version"
  end
end
